- hosts: namenode
  vars:
    namenode_dir: "/nn"
  roles:
  - role: /root/hadoop-ws/namenode

- hosts: datanode
  vars:
    datanode_dir: "/dn"
  roles:
  - role: /root/hadoop-ws/datanode

- hosts: jobtracker
  roles:
  - role: /root/hadoop-ws/jobtracker

- hosts: tasktracker
  roles:
  - role: /root/hadoop-ws/tasktracker

- hosts: client
  roles:
  - role: /root/hadoop-ws/client
